<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb9b44e5bb52030d1873f6564adfe90d5
{
    public static $prefixLengthsPsr4 = array (
        'c' => 
        array (
            'cebe\\markdown\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'cebe\\markdown\\' => 
        array (
            0 => __DIR__ . '/..' . '/cebe/markdown',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb9b44e5bb52030d1873f6564adfe90d5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb9b44e5bb52030d1873f6564adfe90d5::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
